"""
Builds the *** Settings ***, *** Variables ***, *** Keywords *** header block.
Selectors come from the recipe — the LLM never touches them.
"""


def _build_header(base_url: str, recipe: dict) -> str:
    usr = recipe.get("username_selector") or "xpath://input[@placeholder='Username']"
    pwd = recipe.get("password_selector") or "xpath://input[@type='password']"
    btn = recipe.get("submit_selector")   or "xpath://*[@type='submit']"
    success = recipe.get("success_indicator", "")
    success_wait = (
        f"    Run Keyword And Return Status    Wait Until Page Contains    {success}    8s\n"
        if success else ""
    )

    return (
        "*** Settings ***\n"
        "Library    SeleniumLibrary\n"
        "Library    rf_agent.healing.runtime_healer\n"
        "Test Teardown    Run Keyword And Ignore Error    Close All Browsers\n"
        "\n"
        "*** Variables ***\n"
        f"${{BASE_URL}}    {base_url}\n"
        "${SCREENSHOT_ROOT}    output/screenshots\n"
        "\n"
        "*** Keywords ***\n"
        "Open App And Login\n"
        "    [Arguments]    ${username}    ${password}\n"
        "    ${_safe}=    Evaluate    ''.join('_' if c in r'<>:\"/\\|?*()' else c for c in \"\"\"${TEST NAME}\"\"\")\n"
        "    Open Browser    ${BASE_URL}    chrome    "
        "options=add_argument(\"--incognito\");add_argument(\"--disable-popup-blocking\")\n"
        "    Set Window Size    1920    1080\n"
        "    Set Screenshot Directory    ${SCREENSHOT_ROOT}\n"
        "    Sleep    3s\n"
        "    Capture Page Screenshot    ${_safe}_initial.png\n"
        f"    Wait Until Element Is Visible    {usr}    15s\n"
        f"    Input Text    {usr}    ${{username}}\n"
        f"    Wait Until Element Is Visible    {pwd}    15s\n"
        f"    Input Text    {pwd}    ${{password}}\n"
        f"    Wait Until Element Is Visible    {btn}    15s\n"
        f"    Click Element    {btn}\n"
        "    Sleep    2s\n"
        f"{success_wait}"
        "    Capture Page Screenshot    ${_safe}_after_login.png\n"
        "\n"
        "Open Browser Only\n"
        "    Open Browser    ${BASE_URL}    chrome    "
        "options=add_argument(\"--incognito\");add_argument(\"--disable-popup-blocking\")\n"
        "    Set Window Size    1920    1080\n"
        "    Set Screenshot Directory    ${SCREENSHOT_ROOT}\n"
        "\n"
        "Resolved Selector\n"
        "    [Arguments]    ${label}    ${role}    ${primary}\n"
        "    ${ok}=    Run Keyword And Return Status    Wait Until Element Is Visible    ${primary}    15s\n"
        "    IF    ${ok}\n"
        "        RETURN    ${primary}\n"
        "    END\n"
        "    Log    Healing '${label}' (${role}) — primary selector not visible    level=WARN\n"
        "    ${new}=    Heal Selector By Label    ${label}    ${role}\n"
        "    Should Not Be Empty    ${new}    Could not heal '${label}' (${role}) — element not on page\n"
        "    Wait Until Element Is Visible    ${new}    10s\n"
        "    RETURN    ${new}\n"
        "\n"
        "Smart Click\n"
        "    [Arguments]    ${label}    ${role}    ${primary}\n"
        "    ${sel}=    Resolved Selector    ${label}    ${role}    ${primary}\n"
        "    Click Element    ${sel}\n"
        "\n"
        "Smart Input\n"
        "    [Arguments]    ${label}    ${role}    ${primary}    ${value}\n"
        "    ${sel}=    Resolved Selector    ${label}    ${role}    ${primary}\n"
        "    Input Text    ${sel}    ${value}\n"
        "\n"
        "Smart Wait\n"
        "    [Arguments]    ${label}    ${role}    ${primary}\n"
        "    Resolved Selector    ${label}    ${role}    ${primary}\n"
        "\n"
        "Smart Select By Label\n"
        "    [Arguments]    ${label}    ${role}    ${primary}    ${value}\n"
        "    ${ok}=    Run Keyword And Return Status    Wait Until Page Contains Element    ${primary}    15s\n"
        "    ${sel}=    Set Variable If    ${ok}    ${primary}    ${EMPTY}\n"
        "    IF    not ${ok}\n"
        "        ${sel}=    Heal Selector By Label    ${label}    ${role}\n"
        "        Should Not Be Empty    ${sel}    Could not heal '${label}' (${role}) — select not on page\n"
        "        Wait Until Page Contains Element    ${sel}    10s\n"
        "    END\n"
        "    Select From List By Label    ${sel}    ${value}\n"
        "\n"
        "*** Test Cases ***"
    )
