import os
import requests
from dotenv import load_dotenv

load_dotenv()

TRELLO_API_KEY = os.getenv("TRELLO_API_KEY")
TRELLO_TOKEN = os.getenv("TRELLO_TOKEN")
TRELLO_BOARD_ID = os.getenv("TRELLO_BOARD_ID")

BASE_URL = "https://api.trello.com/1"


def _get_long_board_id():
    """Resolve short board ID to long board ID."""
    url = f"{BASE_URL}/boards/{TRELLO_BOARD_ID}"
    params = {"key": TRELLO_API_KEY, "token": TRELLO_TOKEN}
    resp = requests.get(url, params=params)
    resp.raise_for_status()
    return resp.json()["id"]


def _get_or_create_list(list_name="🐛 Bugs - QA Agent"):
    """
    Get or create a list on the Trello board for failed test cards.
    Returns the list ID.
    """
    long_id = _get_long_board_id()
    url = f"{BASE_URL}/boards/{long_id}/lists"
    params = {"key": TRELLO_API_KEY, "token": TRELLO_TOKEN}
    resp = requests.get(url, params=params)
    resp.raise_for_status()

    for lst in resp.json():
        if lst["name"] == list_name:
            return lst["id"]

    # Create the list if it doesn't exist
    create_url = f"{BASE_URL}/lists"
    create_params = {
        "key": TRELLO_API_KEY,
        "token": TRELLO_TOKEN,
        "name": list_name,
        "idBoard": long_id,
        "pos": "bottom"
    }
    create_resp = requests.post(create_url, params=create_params)
    create_resp.raise_for_status()
    return create_resp.json()["id"]


def _attach_screenshot(card_id, screenshot_path):
    """Attach a screenshot image to a Trello card."""
    url = f"{BASE_URL}/cards/{card_id}/attachments"
    params = {"key": TRELLO_API_KEY, "token": TRELLO_TOKEN}
    with open(screenshot_path, "rb") as f:
        files = {"file": (os.path.basename(screenshot_path), f, "image/png")}
        resp = requests.post(url, params=params, files=files)
        resp.raise_for_status()
    return resp.json()


def create_failure_card(test_id, error_details, screenshot_path=None):
    """
    Create a Trello card for a failed test case.
    Falls back to mock mode if Trello credentials are not configured.
    """
    # Fallback to mock if credentials are missing
    if not all([TRELLO_API_KEY, TRELLO_TOKEN, TRELLO_BOARD_ID]):
        print(f"[TRELLO MOCK] Creating card for {test_id}")
        print(f"  - Error: {error_details}")
        if screenshot_path:
            print(f"  - Screenshot: {screenshot_path}")
        return {"card_id": "mock_id", "status": "mock"}

    try:
        list_id = _get_or_create_list()

        # Create the card
        url = f"{BASE_URL}/cards"
        params = {
            "key": TRELLO_API_KEY,
            "token": TRELLO_TOKEN,
            "idList": list_id,
            "name": f"🔴 {test_id} - FAILED",
            "desc": (
                f"## Test Case Failed\n\n"
                f"**Test ID:** {test_id}\n\n"
                f"**Error:**\n```\n{error_details}\n```\n\n"
                f"---\n"
                f"*Generated by QA Agent*"
            ),
            "pos": "top"
        }

        # Add a red label
        label_url = f"{BASE_URL}/boards/{TRELLO_BOARD_ID}/labels"
        label_params = {"key": TRELLO_API_KEY, "token": TRELLO_TOKEN}
        labels_resp = requests.get(label_url, params=label_params)
        if labels_resp.ok:
            red_labels = [l for l in labels_resp.json() if l.get("color") == "red"]
            if red_labels:
                params["idLabels"] = red_labels[0]["id"]

        resp = requests.post(url, params=params)
        resp.raise_for_status()
        card = resp.json()
        card_id = card["id"]

        print(f"[TRELLO] ✅ Card created: {card['shortUrl']}")

        # Attach screenshot if available
        if screenshot_path and os.path.exists(screenshot_path):
            _attach_screenshot(card_id, screenshot_path)
            print(f"[TRELLO] 📎 Screenshot attached to card.")

        return {"card_id": card_id, "url": card["shortUrl"], "status": "created"}

    except Exception as e:
        print(f"[TRELLO] ❌ Error creating card: {e}")
        return {"card_id": None, "status": "error", "error": str(e)}
